// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmtnmisdmchydrriuont.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtdG5taXNkbWNoeWRycml1b250Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4ODE4NTEsImV4cCI6MjA4ODQ1Nzg1MX0.NvTHq4rcECgd6Yd7teZXJ-DSeJr0do0QYnak9344o5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});